// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgbfpsdiyghuxcxhvcpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnYmZwc2RpeWdodXhjeGh2Y3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTMzMDMsImV4cCI6MjA2MDM2OTMwM30.5VH4TsrKXvdF4vSZz-4Oh4hi6xFHoGBYOETXeHyAm9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);